import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {buildAnalysis} from '../src/analyze.mjs';import {execute} from '../src/engine.mjs';import {HARD} from '../src/input.mjs';import {sha256,strictJSON} from '../src/codec.mjs';import {preflightMF1} from '../src/preflight.mjs';
const manifest=fs.readFileSync(new URL('../examples/manifest.json',import.meta.url)),cat=fs.readFileSync(new URL('../examples/files.json',import.meta.url));
function worked(limits){const m=JSON.parse(manifest);if(limits)m.limits={...HARD,...limits};return {manifestBytes:Buffer.from(JSON.stringify(m)),catalogsById:new Map(['en','fr','ja'].map(k=>[k,cat]))};}
function single(text,variables=[]){const c=Buffer.from(JSON.stringify({kind:'branchlingo-catalog',schemaVersion:1,messages:[{id:'m',text}]}));return {manifestBytes:Buffer.from(JSON.stringify({kind:'branchlingo-manifest',schemaVersion:1,profile:'formatjs-mf1-finite-v1',catalogs:[{id:'c',locale:'en',path:'c.json',sha256:sha256(c)}],contracts:[{messageId:'m',variables}]})),catalogsById:new Map([['c',c]])};}
test('reducible work ceilings refuse before analysis/render and accept exact estimates',()=>{const base=buildAnalysis(worked());for(const [key,value] of Object.entries({dispatchEvaluations:base.counts.dispatchEvaluations,maskWordOps:base.counts.maskWordOps,arms:21,witnessCases:21,astNodes:base.scopes.reduce((a,s)=>a+s.nodes,0),renderWork:base.estimates.renderUpper})){assert.throws(()=>buildAnalysis(worked({[key]:value-1})),e=>e.status==='incomplete',key);assert.doesNotThrow(()=>buildAnalysis(worked({[key]:value})),key);}assert.equal(execute('generate',worked({packBytes:1})).status,'incomplete');});
test('huge intervals, offset overflow, raw limits and malformed deep JSON fail safely',()=>{const v=[{name:'n',domain:{kind:'integer-range',min:0,max:10001}}];assert.equal(execute('generate',single('{n,plural,other{x}}',v)).status,'incomplete');v[0].domain.max=Number.MAX_SAFE_INTEGER;assert.equal(execute('generate',single('{n,plural,other{x}}',v)).status,'incomplete');v[0].domain.min=Number.MAX_SAFE_INTEGER;assert.equal(execute('generate',single('{n,plural,offset:-1 other{x}}',v)).status,'invalid');assert.throws(()=>strictJSON(Buffer.alloc(2*1024*1024+1),{maxBytes:2*1024*1024}));assert.throws(()=>preflightMF1('x'.repeat(65537)),e=>e.status==='incomplete');});
test('output and marker bounds produce incomplete, never a coverage claim',()=>{const variables=[{name:'x',domain:{kind:'sample',value:'X'.repeat(4096)}}];const tooLong=execute('generate',single('{x}'.repeat(257),variables));assert.equal(tooLong.status,'incomplete');assert.equal(tooLong.coverageClaim,undefined);variables[0].domain.value='\ue000'.repeat(4096);const marked=execute('generate',single('{x}'.repeat(80)+'{s,select,a{x}other{x}}',[...variables,{name:'s',domain:{kind:'string-enum',values:['a','b']}}]));assert.equal(marked.status,'incomplete');assert.equal(marked.coverageClaim,undefined);});
test('bounds apply across catalog occurrences and aggregate domains',()=>{const variables=Array.from({length:10},(_,i)=>({name:'n'+i,domain:{kind:'integer-range',min:0,max:10000}}));assert.equal(execute('generate',single(variables.map(v=>'{'+v.name+'}').join(''),variables)).status,'incomplete');const text=Array.from({length:1025},(_,i)=>`k${i}{x}`).join('');assert.throws(()=>preflightMF1('{s,select,'+text+'other{x}}'),e=>e.status==='incomplete');});
